name: on-push

on: ['push']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: ğŸ” ci
    runs-on:
      labels: ubuntu-latest

    steps:
      - name: ğŸ”¸ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: ğŸ¦„ Prettier
        run: yarn prettier --check

      - name: ğŸ”¬ Lint
        run: yarn lint

      - name: ğŸ“ Test
        run: yarn test

      - name: ğŸ‘· Build
        run: yarn build
        env:
          DATABASE_URL: postgresql://root:@127.0.0.1:26257/db
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_ZmFuY3ktY293LTc5LmNsZXJrLmFjY291bnRzLmRldiQ
          CLERK_SECRET_KEY: not-needed

      - name: Stop DB
        if: always()
        run: docker-compose -f ./dev/docker/docker-compose-test.yml down
