name: on-push

on: ['push']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: ğŸ” ci

    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}

    runs-on:
      labels: ubuntu-latest

    steps:
      - name: ğŸ”¸ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install turso
        run: ./setup/install-turso.sh

      - name: Install dependencies
        run: bun install

      - name: ğŸ¦„ Format
        run: bun run format:check

      - name: ğŸ”¬ Lint
        run: bun run lint

      - name: ğŸ“ Test
        run: export PATH="/home/runner/.turso:$PATH" && bun test

#      - name: ğŸ‘· Build
#        run: bun run build
